# Optional arguments with defaults
start_idx: -1 
end_idx: -1 
GO_term_contains: "kinase" # Default is None, replace with string if needed

# Flags (boolean, default to false)
no_log_wandb: false  # Set to true if you don't want to log results to Weights and Biases

defaults:
  - _self_
  - sample: sample_latent
  - decode: default
