defaults:
  - _self_

cond_code: ???
npz_timestamp: ???
plaid_model_id: "5j007z42" 

npz_path: /data/lux70/plaid/artifacts/samples/${plaid_model_id}/${cond_code}/${npz_timestamp}/latent.npz
output_root_dir: /data/lux70/plaid/artifacts/samples/${plaid_model_id}/${cond_code}/${npz_timestamp}/generated
batch_size: 64 
device: "cuda"
num_recycles: 1