model_id: "5j007z42"
model_ckpt_dir: "/data/lux70/plaid/checkpoints/plaid-compositional"
organism_idx: 3617 
function_idx: 2219 
cond_scale: 10.
num_samples: 1024 
beta_scheduler_name: null 
beta_scheduler_start: null
beta_scheduler_end: null
beta_scheduler_tau: null

sampling_timesteps: 20

batch_size: -1 
return_all_timesteps: False 
output_root_dir: "/data/lux70/plaid/artifacts/samples/dpm2m"

# length must be divisible by 4.
# the actual protein length will be 2 * length.
length: 128

# DPM-Solver specific parameters
t_start: null
t_end: null
order: 2
skip_type: 'time_uniform'
method: 'multistep' # ['multistep', 'single_step' (i.e. DPM-Solver-Fast)]
lower_order_final: True
denoise_to_zero: False
solver_type: 'dpmsolver'
atol: 0.0078
rtol: 0.05