# Full pipeline:
# 1. Sample latent from conditioning
# --> 1b. Calculate FID
# 2a. Generate: latent to sequence
# 2b. Generate: latent to structure
# --> 2c. Log perplexity and pLDDT
# 3a. Inverse reconstruct: generated sequence to reconstructed structure
# 3b. Inverse reconstruct: generated structure to reconstructed sequence
# --> 3c. Calculate ccSR and ccRMSD.
# 4a. Phantom reconstruct: generated sequence to phantom structure
# 4b. Phantom reconstruct: generated structure to phantom sequence
# --> 4c. Calculate scSR and scRMSD. 

# sample_latent: False

# f2219_o3617
function_idx: 2219
organism_idx: 3617

calculate_fid: False
decode_latent: False
log_perplexity_and_plddt: False
inverse_generate_sequence: False
inverse_generate_structure: False
calculate_ccsr_and_ccrmsd: False
phantom_reconstruct_generated_sequence_to_phantom_structure: False
phantom_reconstruct_generated_structure_to_phantom_sequence: False
calculate_scsr_and_scrmsd: False

defaults:
  - _self_
  - decode_latent_config: decode_latent
  - sample_latent_config: sample_latent
  - inverse_generate_sequence_config: inverse_fold
  - inverse_generate_structure_config: esmfold
  - phantom_generate_sequence_config: null
  - phantom_generate_structure_config: null