uid: null

run_decode: True
run_cross_consistency: True
run_self_consistency: True

defaults:
  - _self_
  - decode: default
  - sample: ddim_unconditional 
  - inverse_generate_sequence: default
  - inverse_generate_structure: esmfold
  - phantom_generate_sequence: default
  - experiment: null