defaults:
  - _self_

model_id: "4hdab8dn"
model_ckpt_dir: "/data/lux70/plaid/checkpoints/plaid-compositional"
organism_idx: 3617 
function_idx: 2219 
cond_scale: 7.
num_samples: 1024 
beta_scheduler_name: null 
sampling_timesteps: 1000 
batch_size: 1024 
return_all_timesteps: False 
output_root_dir: "/data/lux70/plaid/artifacts/samples"

# length must be divisible by 4.
# the actual protein length will be 2 * length.
length: 64