_target_: plaid.datasets.TokenDataset

compress_model_id: "2024-03-05T06-20-52"  # soft-violet
token_dir: /homefs/home/lux70/storage/data/cath/tokens/
max_seq_len: 128 
batch_size: 256
num_workers: 1
shuffle_val_dataset: False
