_target_: lightning.pytorch.Trainer
accelerator: gpu 
strategy: ddp
devices: -1
num_nodes: 1 
precision: bf16-mixed

gradient_clip_val: 0.5
log_every_n_steps: 50 
num_sanity_val_steps: 0
gradient_clip_algorithm: norm

max_epochs: 20000
default_root_dir: ${paths.log_dir}
check_val_every_n_epoch: 1000

# accumulate_grad_batches: 1