_target_: lightning.pytorch.Trainer
accelerator: gpu
devices: [6]
gradient_clip_val: 2.0
gradient_clip_algorithm: norm
precision: bf16-mixed
limit_val_batches: 10
num_sanity_val_steps: 2
# default_root_dir: hdfs://hdfs:9000/user/username/lightning_logs