_target_: lightning.pytorch.Trainer
accelerator: gpu
devices: -1
gradient_clip_val: 0.5
log_every_n_steps: 30 
num_sanity_val_steps: 0
gradient_clip_algorithm: norm
max_epochs: 20000
default_root_dir: ${paths.log_dir}

# accelerator='auto'
# strategy='auto'
# devices='auto'
# num_nodes=1
# precision=None
# logger=None
# callbacks=None
# fast_dev_run=False
# max_epochs=None
# min_epochs=None
# max_steps=-1
# min_steps=None
# max_time=None
# limit_train_batches=None
# limit_val_batches=None
# limit_test_batches=None
# limit_predict_batches=Nonp
# overfit_batches=0.0
# val_check_interval=None
# check_val_every_n_epoch=1
# num_sanity_val_steps=None
# log_every_n_steps=None
# enable_checkpointing=None
# enable_progress_bar=None
# enable_model_summary=None
# accumulate_grad_batches=1
# gradient_clip_val=None
# gradient_clip_algorithm=None
# deterministic=None
# benchmark=None
# inference_mode=True
# use_distributed_sampler=True
# profiler=None
# detect_anomaly=False
# barebones=False
# plugins=None
# sync_batchnorm=False
# reload_dataloaders_every_n_epochs=0
# default_root_dir=None

# # default_root_dir: hdfs://hdfs:9000/user/username/lightning_logs