_target_: lightning.pytorch.Trainer
accelerator: gpu
strategy: ddp_find_unused_parameters_true
devices: -1 
gradient_clip_val: 2.0
gradient_clip_algorithm: norm
precision: bf16-mixed
num_sanity_val_steps: 2
max_epochs: 5000
fast_dev_run: False
# limit_val_batches: 10
# overfit_batches: 2 
# default_root_dir: hdfs://hdfs:9000/user/username/lightning_logs