name: plaid
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
dependencies:
  - python==3.11
  - pip
  - pytorch-cuda=12.1
  - pytorch
  - bioconda::tmalign
  - pip:
    - -r requirements.txt