name: plaid
channels:
  - nvidia
  - conda-forge
  - bioconda
  - salilab
  - pytorch
dependencies:
  - python==3.10
  - pip
  - gcc
  - cuda-toolkit
  - pytorch
  - pytorch-cuda=12.1
  - libjpeg-turbo
  - libpng
  - torchvision
  - torchaudio
  - bioconda::tmalign
  - salilab::dssp
  - pip:
    - -r requirements.txt
