name: plaid
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
dependencies:
  - python==3.10
  - pip
  - pytorch-cuda=12.1
  - pytorch
  - bioconda::tmalign
  - gxx_linux-64=11.2.0
  - pip:
    - -r requirements.txt