_target_: plaid.compression.HourglassVQLightningModule

dim: 1024
depth: [4, 2, 4]
shorten_factor: 2
downproj_factor: 2
attn_resampling: true
updown_sample_type: 'linear'
heads: 8
dim_head: 64
causal: false
norm_out: false 

seq_loss_weight: 0.0
struct_loss_weight: 0.0
log_sequence_loss: False
log_structure_loss: False

lr: 1e-4
lr_sched_type: "constant"
lr_num_warmup_steps: 0
lr_num_training_steps: 10_000_000
lr_num_cycles: 1