_target_: plaid.compression.hourglass_vq.HourglassVQLightningModule

dim: 1024
depth: 12
shorten_factor: 1 
downproj_factor: 1
attn_resampling: true
updown_sample_type: 'linear'
heads: 12
dim_head: 64
norm_out: false 
use_quantizer: true

seq_loss_weight: 0.0
struct_loss_weight: 0.0
log_sequence_loss: False 
log_structure_loss: False

lr: 1e-4
lr_sched_type: "constant_with_warmup"
lr_num_warmup_steps: 3000
lr_num_training_steps: 10_000_000
lr_num_cycles: 1