_target_: plaid.denoisers.FunctionOrganismDiT

hidden_size: 768 
max_seq_len: 512
depth: 12 
num_heads: 12
mlp_ratio: 4.0
use_self_conditioning: True

# 134M parameters
# max batch size (sequence length 512): 128
# max batch size (sequence length 128): 1024