_target_: plaid.denoisers.FunctionOrganismUDiT

hidden_size: 2048 
max_seq_len: 256
depth: 21
num_heads: 16
mlp_ratio: 4.0
use_self_conditioning: True

timestep_embedding_strategy: "sinusoidal"
use_skip_connect: True 
attention_mode: "xformers_memory_efficient"