_target_: plaid.denoisers.FunctionOrganismUDiT

hidden_size: 1280
max_seq_len: 256
depth: 30
num_heads: 16
mlp_ratio: 4.0
use_self_conditioning: True

timestep_embedding_strategy: "fourier"
use_skip_connect: True
attention_mode: "xformers"
