_target_: plaid.denoisers.FunctionOrganismUDiT

hidden_size: 1280
max_seq_len: 256
depth: 28 
num_heads: 16
mlp_ratio: 4.0
use_self_conditioning: True

timestep_embedding_strategy: "sinusoidal"
use_skip_connect: False 
attention_mode: "xformers_memory_efficient"

# 900M parameters