_target_: plaid.denoisers.UTriSelfAttnDenoiser

hid_dim: 1024
num_blocks: 13 
conditioning_strategy: "hidden_concat"
timestep_embedding_strategy: "fourier"
pos_embedding_strategy: "rotary"
use_self_conditioning: True 
use_skip_connections: True
label_num_classes: null
cfg_dropout: 0.0