_target_: plaid.datasets.FunctionOrganismDataModule

train_shards: "/data/lux70/data/pfam/compressed/jzlv54wl/train/shard{00000..00007}.tar"
val_shards: "/data/lux70/data/pfam/compressed/jzlv54wl/val/shard{00000..00001}.tar"

config_file: "/data/lux70/data/pfam/compressed/jzlv54wl/config.json"
go_metadata_fpath: "/data/lux70/data/pfam/pfam2go.csv"
organism_metadata_fpath: "/data/lux70/data/pfam/organism_counts.csv"
cache_dir: "/data/lux70/data/pfam/compressed/jzlv54wl/cache/"

train_epoch_num_samples: null
val_epoch_num_samples: null
shuffle_buffer: 1000
shuffle_initial: 1000

max_length: 512
batch_size: 64
num_workers: 1
