timestamp: ${now:%Y-%m-%d}T${now:%H-%M-%S}

checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${paths.checkpoint_dir}/diffusion/${callbacks.checkpoint.timestamp}
  filename: "{epoch}-{step}"
  verbose: true
  save_last: true
  every_n_train_steps: 5000