_target_: lightning.pytorch.callbacks.ModelCheckpoint
save_last: link
filename: "{epoch}-{step}"
verbose: true
every_n_train_steps: 5000
monitor: "step"
save_top_k: 1
mode: "max"
auto_insert_metric_name: false
