_target_: plaid.ema.EMAModelCheckpoint
dirpath: null # directory to save the model file
filename: "{epoch}-{step}"
verbose: true
save_last: False 
every_n_train_steps: 5000
max_keep_ckpts: 2  # also keep EMA