_target_: plaid.ema.EMAModelCheckpoint
dirpath: null # directory to save the model file
filename: "{epoch}-{step}"
verbose: true
save_last: false
every_n_train_steps: 5000
monitor: "step"
save_top_k: 1
mode: "max"
auto_insert_metric_name: false
