_target_: lightning.pytorch.callbacks.ModelCheckpoint
dirpath: null 
filename: "{epoch}-{step}"
verbose: true
save_last: "link" 
every_n_train_steps: 5000
monitor: 'val/loss'
auto_insert_metric_name: false
mode: min