_target_: plaid.denoisers.ClassifierFreeGuidanceDiT

input_dim: ${input_dim}
hidden_size: 1024 
max_seq_len: 512
depth: 12 
num_heads: 16
mlp_ratio: 4.0
use_self_conditioning: False 
class_dropout_prob: 0.1
num_classes: 659