cond_code: ""
npz_timestamp: ""
plaid_model_id: "5j007z42" 

fasta_file: /data/lux70/plaid/artifacts/samples/${plaid_model_id}/${cond_code}/${npz_timestamp}/inverse_generated/sequences.fasta
outdir: /data/lux70/plaid/artifacts/samples/${plaid_model_id}/${cond_code}/${npz_timestamp}/phantom_generated/structures