_target_: lightning.pytorch.loggers.WandbLogger

project: plaid-hourglass-2
entity: ${paths.entity}
name: null
tags: null
group: null


    # job_type: Optional[str] = None,
    # dir: Optional[StrPath] = None,
    # config: Union[Dict, str, None] = None,
    # project: Optional[str] = None,
    # entity: Optional[str] = None,
    # reinit: Optional[bool] = None,
    # tags: Optional[Sequence] = None,
    # group: Optional[str] = None,
    # name: Optional[str] = None,
    # notes: Optional[str] = None,
    # magic: Optional[Union[dict, str, bool]] = None,
    # config_exclude_keys: Optional[List[str]] = None,
    # config_include_keys: Optional[List[str]] = None,
    # anonymous: Optional[str] = None,
    # mode: Optional[str] = None,
    # allow_val_change: Optional[bool] = None,
    # resume: Optional[Union[bool, str]] = None,
    # force: Optional[bool] = None,
    # tensorboard: Optional[bool] = None,
    # sync_tensorboard: Optional[bool] = None,
    # monitor_gym: Optional[bool] = None,
    # save_code: Optional[bool] = None,
    # id: Optional[str] = None,
    # settings: Union[Settings, Dict[str, Any], None] = None