_target_: plaid.vqvae.VQVAE

in_dim: 1024
h_dim: 256
res_h_dim: 256
n_res_layers: 8
n_embeddings: 512
embedding_dim: 64
beta: 0.25

lr: 1e-4
lr_beta1: 0.9
lr_beta2: 0.999
lr_num_warmup_steps: 0
lr_num_training_steps: 1_000_000
