root_dir: /shared/amyxlu/plaid
data_dir: /shared/amyxlu/data
log_dir: /shared/amyxlu/plaid/logs
project_dir: /home/amyxlu/code/plaid
checkpoint_dir: ${paths.root_dir}/checkpoints
artifacts_dir: ${paths.root_dir}/artifacts
entity: amyxlu