project_dir: /homefs/home/lux70/code/plaid
bucket_dir: /mp/lux70/plaid
data_dir: /data/lux70/data
home_dir: /homefs/home/lux70

log_dir: ${paths.bucket_dir}/logs
checkpoint_dir: ${paths.bucket_dir}/checkpoints
artifacts_dir: ${paths.bucket_dir}/artifacts

entity: lu-amy-al1