defaults:
  - _self_

cond_code: "" 
npz_timestamp: "" 
plaid_model_id: "5j007z42" 

pdb_dir: /data/lux70/plaid/artifacts/samples/${plaid_model_id}/${cond_code}/${npz_timestamp}/inverse_generated
outdir: /data/lux70/plaid/artifacts/samples/${plaid_model_id}/${cond_code}/${npz_timestamp}/phantom_generated
verbose: true
model_name: "v_48_002"
ca_only: true
num_seq_per_target: 8
sampling_temp: "0.1"
save_score: false
save_probs: false
score_only: false
conditional_probs_only: false
conditional_probs_only_backbone: false