defaults:
  - _self_

checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${paths.checkpoint_dir}
  filename: "{epoch}-{step}"
  verbose: true
  save_last: true
  every_n_train_steps: 5000

sample:
  _target_: plaid.callbacks.SampleCallback
  outdir: ${paths.artifacts_dir}/samples
  n_to_sample: 16
  n_to_construct: -1
  batch_size: -1
  calc_structure: False
  calc_perplexity: True
  num_recycles: 4

lr_monitor:
  _target_: lightning.pytorch.callbacks.LearningRateMonitor
  logging_interval: step
  log_momentum: true
  log_weight_decay: true