_target_: plaid.callbacks.SampleCallback

fid_holdout_tensor_fpath: ${paths.data_dir}/rocklin/shards/val/esmfold/seqlen_256/fp32/shard0000.h5

# make seq len explicitly to match
uncompress_for_fid: False
normalize_real_features: False

n_to_sample: 64
batch_size: 64
gen_seq_len: 128 

n_to_construct: 16

calc_sequence: True
calc_structure: True
calc_perplexity: True
calc_fid: False 

log_to_wandb: True

outdir: ${paths.artifacts_dir}/sampled
save_generated_structures: True 
run_every_n_steps: 500 
n_structures_to_log: 4
