_target_: plaid.callbacks.SampleCallback

fid_holdout_tensor_fpath: /homefs/home/lux70/plaid_cached_tensors/uniref_esmfold_feats.st
normalize_real_features: True 

n_to_sample: 128 
batch_size: 64
gen_seq_len: 128 

n_to_construct: 16

calc_sequence: True
calc_structure: True
calc_perplexity: True
calc_fid: True 

log_to_wandb: True

outdir: ${paths.artifacts_dir}/sampled
save_generated_structures: True 
run_every_n_steps: 500 
n_structures_to_log: 4
