resume_from_model_id: null
compression_model_id: null
compression_ckpt_dir: null
shorten_factor: null
use_compile: true

defaults:
  - _self_
  - paths: pcluster 
  - datamodule: compressed/pfam_h5_n1M.yaml
  - denoiser: cfg/base.yaml
  - beta_scheduler: vdiffusion
  - latent_scaler: esmfold
  - diffusion: edm
  - trainer: default
  - callbacks/checkpoint: edm
  - callbacks/lr_monitor: default
  - callbacks/sample: pfam_compressed_fid 
  - logger: diffusion
  - experiment: null

dryrun: false 
run_test: null
