defaults:
  - _self_
  - paths: pcluster 
  - trainer: default
  - datamodule: /compressed/pfam_h5
  - denoiser: dit
  - diffusion: diffusion
  - callbacks/checkpoint: diffusion
  - callbacks/lr_monitor: default
  - callbacks/sample: pfam_compressed_fid 
  - callbacks/batch_size: default
  - logger: diffusion
  - experiment: null

dryrun: False 
run_test: null

resume_from_model_id: null
compression_model_id: null
compression_ckpt_dir: null
shorten_factor: null

run_sample_callback: true
run_batch_size_callback: false