defaults:
  - _self_
  - paths: pcluster 
  - trainer: default
  - datamodule: ...
  - denoiser: ...
  - diffusion: ...
  - callbacks/checkpoint: ...
  - callbacks/lr_monitor: default
  - logger: ... 
  - experiment: null

resume_from_model_id: null
compression_model_id: null
