defaults:
  - _self_
  - paths: pcluster 
  - datamodule: cath_h5
  - hourglass: vq
  - latent_scaler: esmfold 
  - trainer: default
  - callbacks/checkpoint: hourglass_vq 
  - callbacks/lr_monitor: default
  - callbacks/compression: default
  - logger: hourglass_vq
  - experiment: null

dryrun: False 
run_test: null

run_structure_eval: False