timestamp: ${now:%Y-%m-%d}T${now:%H-%M-%S}

defaults:
  - _self_
  - paths: pcluster 
  - datamodule: cath_h5
  - denoiser: utsa
  - beta_scheduler: adm_cosine 
  - latent_scaler: cath
  - diffusion: diffusion
  - trainer: default
  - callbacks/checkpoint: diffusion
  - callbacks/lr_monitor: default
  - callbacks/sample: default
  - logger: diffusion
  - experiment: null

dryrun: False 
run_test: null