defaults:
  - _self_
  - paths: dgx5
  - datamodule: uniref_fasta
  - sequence_decoder: default
  - trainer: default
  - callbacks/checkpoint: sequence_decoder
  - callbacks/lr_monitor: default
  - logger: sequence_decoder
  - experiment: null

timestamp: ${now:%Y-%m-%d}T${now:%H-%M-%S}
callbacks/checkpoint:
  - dirpath: ${paths.root_dir}/checkpoints/sequence_decoder/${timestamp}

dryrun: False 
run_test: null