defaults:
  - _self_
  - paths: dgx5
  - datamodule: cath
  - vqvae: patched_vqvae 
  - trainer: default
  - callbacks: default
  - logger: vqvae
  - experiment: null

callbacks.checkpoint.dirpath: ${paths.checkpoint_dir}/vqvae

dryrun: False 
run_test: null