defaults:
  - _self_
  - paths: pcluster 
  - datamodule: seqrep_cached/cath_h5
  - hourglass: vq
  - trainer: default
  - callbacks/checkpoint: hourglass_vq 
  - callbacks/lr_monitor: default
  - callbacks/compression: default
  - logger: hourglass_vq
  - experiment: null

dryrun: False 
run_test: null

resume_from_model_id: null
use_compression_callback: true