timestamp: ${now:%Y-%m-%d}T${now:%H-%M-%S}

defaults:
  - _self_
  - paths: dgx5
  - datamodule: cath_safetensors
  - vqvae: patched_vqvae 
  - trainer: default
  - callbacks/checkpoint: vqvae 
  - callbacks/lr_monitor: default
  - logger: vqvae
  - experiment: null

dryrun: False 
run_test: null