defaults:
  - _self_
  - paths: pcluster 
  - trainer: default
  - datamodule: /compressed/pfam_h5
  - denoiser: dit
  - beta_scheduler: adm_cosine 
  - latent_scaler: esmfold 
  - diffusion: diffusion
  - callbacks/checkpoint: diffusion # ema
  - callbacks/lr_monitor: default
  - callbacks/sample: pfam_compressed_fid 
  - callbacks/ema: default
  - logger: diffusion
  - experiment: null

dryrun: False 
run_test: null

resume_from_model_id: null
compression_model_id: null
compression_ckpt_dir: null
shorten_factor: null
run_sample_callback: true