timestamp: ${now:%Y-%m-%d}T${now:%H-%M-%S}

make_structure_constructor: False
make_sequence_constructor: True

defaults:
  - _self_
  - paths: pcluster 
  - datamodule: cath_h5
  - hourglass: esmfold
  - latent_scaler: esmfold 
  - trainer: default
  - callbacks/checkpoint: hourglass 
  - logger: hourglass
  - experiment: null


dryrun: False 
run_test: null