defaults:
  - _self_
  - paths: pcluster 
  - datamodule: cath
  - denoiser: utsa.yaml 
  - beta_scheduler: adm_cosine 
  - latent_scaler: cath
  - diffusion: diffusion
  - trainer: default
  - callbacks: default
  - logger: diffusion
  - experiment: null

timestamp: ${now:%Y-%m-%d}T${now:%H-%M-%S}

callbacks/checkpoint:
  - dirpath: ${paths.root_dir}/checkpoints/diffusion/${timestamp}

callbacks/sample:
  - outdir: ${paths.root_dir}/artifacts/diffusion/${timestamp}

dryrun: False 
run_test: null