defaults:
  - _self_
  - paths: pcluster 
  - datamodule: cath
  - denoiser: utsa.yaml 
  - beta_scheduler: adm_cosine 
  - latent_scaler: cath
  - diffusion: diffusion
  - trainer: default
  - callbacks: default
  - experiment: null

dryrun: False 
run_test: null