defaults:
  - _self_
  - paths: pcluster 
  - datamodule: compressed/rocklin
  - denoiser: utsa
  - beta_scheduler: adm_cosine 
  - latent_scaler: esmfold 
  - diffusion: diffusion
  - trainer: default
  - callbacks/checkpoint: diffusion
  - callbacks/lr_monitor: default
  - callbacks/sample: default
  - logger: diffusion
  - experiment: null

dryrun: False 
run_test: null