timestamp: ${now:%Y-%m-%d}T${now:%H-%M-%S}

defaults:
  - _self_
  - paths: pcluster 
  - datamodule: cath_h5
  - hourglass: vq
  - latent_scaler: esmfold 
  - trainer: default
  - callbacks/checkpoint: hourglass_vq 
  - callbacks/lr_monitor: default
  - logger: hourglass_vq
  - experiment: null

dryrun: False 
run_test: null