defaults:
  - _self_
  - paths: pcluster 
  - datamodule: tokens/v0
  - causal_model: default
  - trainer: default
  - callbacks/checkpoint: default 
  - callbacks/lr_monitor: default
  - logger: causal
  - experiment: null

dryrun: False 
run_test: null