# @package _global_

dataset:
  atom_feature: null
  bond_feature: null
  class: BetaLactamase
  path: /data/lux70/data/torchdrug
  transform:
    class: Compose
    transforms:
    - class: ProteinView
      view: residue
engine:
  batch_size: 64
  gpus:
  - 0
  logger: wandb
eval_metric: spearmanr
fix_encoder: true
optimizer:
  class: Adam
  lr: 5.0e-05
output_dir: /data/lux70/data/torchdrug/outputs
task:
  class: PropertyPrediction
  criterion: mse
  metric:
  - mae
  - rmse
  - spearmanr
  model:
    class: PLAID
    compression_model_id: ??? 
    hourglass_weights_dir: /data/lux70/cheap/checkpoints
  normalization: false
  num_mlp_layer: 2
train:
  num_epoch: 200
