# @package _global_

output_dir: /data/lux70/data/torchdrug/outputs

dataset:
  class: ProteinNet
  path: /data/lux70/data/torchdrug
  atom_feature: null
  bond_feature: null
  transform:
    class: Compose
    transforms:
      - class: TruncateProtein
        max_length: 512 
        random: False
      - class: ProteinView
        view: "residue"

test_split: test
test_batch_size: 1

task:
  class: ContactPrediction
  model:
    class: PLAID
    compression_model_id: ???
    hourglass_weights_dir: /data/lux70/plaid/checkpoints/hourglass_vq
  criterion: bce
  metric: ["accuracy", "prec@L5", "prec@5"]
  max_length: 400
  random_truncate: yes
  threshold: 8.0
  gap: 6
  num_mlp_layer: 2

eval_metric: prec@L5

optimizer:
  class: Adam
  lr: 5.0e-5

fix_encoder: True

engine:
  gpus: [0]
  batch_size: 32 
  logger: wandb

train:
  num_epoch: 150