dataset:
  atom_feature: null
  bond_feature: null
  class: Fold
  path: /data/lux70/data/torchdrug
  transform:
    class: Compose
    transforms:
    - class: ProteinView
      view: residue
engine:
  batch_size: 128
  gpus:
  - 0
  logger: wandb
eval_metric: accuracy
fix_encoder: true
optimizer:
  class: Adam
  lr: 5.0e-05
output_dir: /data/lux70/data/torchdrug/outputs
task:
  class: PropertyPrediction
  criterion: ce
  metric:
  - acc
  - mcc
  model:
    class: PLAID
    compression_model_id: ??? 
    hourglass_weights_dir: /data/lux70/plaid/checkpoints/hourglass_vq
  num_class: 1195
  num_mlp_layer: 2
test_split: test_fold_holdout
train:
  num_epoch: 150 
