output_dir: ~/scratch/torchprotein_output/
dataset:
  class: PPIAffinity
  path: ~/scratch/protein-datasets/
  atom_feature: null
  bond_feature: null
  transform:
    class: Compose
    transforms:
      - class: ProteinView
        view: "residue"
        keys: [ "graph1", "graph2" ]

test_split: test

task:
  class: InteractionPrediction
  model:
    class: PLAID
    compression_model_id: ???
    hourglass_weights_dir: /homefs/home/lux70/storage/plaid/checkpoints/hourglass_vq
  criterion: mse
  metric: [ "mae", "rmse", "spearmanr" ]
  num_mlp_layer: 2
  normalization: False

eval_metric: root mean squared error

optimizer:
  class: Adam
  lr: 5.0e-5

fix_encoder: True
fix_encoder2: True

engine:
  gpus: [0]
  batch_size: 64 
  logger: wandb

train:
  num_epoch: 150
