output_dir: /homefs/home/lux70/storage/data/torchdrug/outputs

dataset:
  class: Solubility
  path: /homefs/home/lux70/storage/data/torchdrug
  atom_feature: null
  bond_feature: null
  transform:
    class: Compose
    transforms:
      - class: ProteinView
        view: "residue"

task:
  class: PropertyPrediction
  model:
    class: PLAID
    compression_model_id: ??? 
    hourglass_weights_dir: /homefs/home/lux70/storage/plaid/checkpoints/hourglass_vq
  criterion: ce
  metric: ["acc", "mcc"]
  num_mlp_layer: 2
  num_class: 2

eval_metric: accuracy

optimizer:
  class: Adam
  lr: 5.0e-5

fix_encoder: True

engine:
  gpus: [0]
  batch_size: 32
  logger: "wandb"

train:
  num_epoch: 50