output_dir: /data/lux70/data/torchdrug/outputs

dataset:
  class: SecondaryStructure
  path: /data/lux70/data/torchdrug
  atom_feature: null
  bond_feature: null
  transform:
    class: Compose
    transforms:
      - class: TruncateProtein
        max_length: 1022
        random: False
      - class: ProteinView
        view: "residue"

test_split: cb513

task:
  class: NodePropertyPrediction
  model:
    class: PLAID
    compression_model_id: ???
    hourglass_weights_dir: /data/lux70/plaid/checkpoints/hourglass_vq
  criterion: ce
  metric: ["micro_acc", "macro_acc"]
  num_mlp_layer: 2
  num_class: 3

eval_metric: macro_acc

optimizer:
  class: Adam
  lr: 5.0e-5

fix_encoder: True

engine:
  gpus: [0]
  batch_size: 32 
  logger: wandb

train:
  num_epoch: 150