_target_: plaid.callbacks.CompressionReconstructionCallback

batch_size: 4
out_dir: ${paths.root_dir}/cache
shard_dir: ${paths.data_dir}/cath/shards
pdb_dir: ${paths.bucket_dir}/cath/dompdb
num_samples: 32
max_seq_len: 256
num_recycles: 4
run_every_n_steps: 10000