_target_: plaid.diffusion.GaussianDiffusionLightningModule

timesteps: 1000
objective: "pred_noise"
min_snr_loss_weight: False
min_snr_gamma: 5
ddim_sampling_eta: 0.0
sampling_timesteps: 500
sampling_seq_len: 64

lr: 1e-4
adam_betas: [0.9, 0.999]