_target_: plaid.diffusion.GaussianDiffusion

timesteps: 1000
objective: "pred_v"
min_snr_loss_weight: True
min_snr_gamma: 5
ddim_sampling_eta: 0.0
sampling_timesteps: 100
sampling_seq_len: 64
x_downscale_factor: 1.0

sequence_decoder_weight: 0.0 
structure_decoder_weight: 0.0
latent_reconstruction_method: "x_recons"

lr: 5e-4
adam_betas: [0.9, 0.999]
lr_sched_type: "constant"
lr_num_warmup_steps: 0
lr_num_training_steps: 10_000_000
lr_num_cycles: 1