_target_: plaid.diffusion.ElucidatedDiffusion

# diffusion
loss_weighting: 'soft-min-snr'
ema_sigma_rels:  [0.05, 0.3]
ema_update_every:  10
ema_checkpoint_every_num_steps:  10

# compression and architecture
shorten_factor: 1.0

# optimization
gradient_accumulation_steps: 1
gradient_clip_val: 0.5

lr: 1e-4
adam_betas: [0.9, 0.999]
lr_sched_type: "constant_with_warmup"
lr_num_warmup_steps: 7000
lr_num_training_steps: 10_000_000
lr_num_cycles: 1