defaults:
  - _self_

fasta_file: "" 
outdir: ""

num_recycles: 1 
max_seq_len: 256
max_num_batches: null
shuffle: False

# if batch size is -1, the whole dataset is processed in one go
batch_size: -1

# mostly for saving animations, e.g. diffusion progress
save_as_single_pdb_file: False