_target_: plaid.pipeline.SampleLatent

model_id: "5j007z42"
model_ckpt_dir: "/data/lux70/plaid/checkpoints/plaid-compositional"
output_root_dir: "/data/lux70/plaid/artifacts/samples"

organism_idx: 3617
function_idx: 2219
cond_scale: 1.0 

num_samples: 128 

beta_scheduler_name: null 
beta_scheduler_start: null
beta_scheduler_end: null
beta_scheduler_tau: null

sampling_timesteps: 500 

batch_size: -1 
length: 256 
return_all_timesteps: True

sample_scheduler: ddim 