# default conditional sampling config

_target_: plaid.pipeline.SampleLatent

model_id: "5j007z42"
model_ckpt_dir: "/data/lux70/plaid/checkpoints/plaid-compositional"
output_root_dir: "/data/lux70/plaid/artifacts/samples/"

organism_idx: 3617
function_idx: 2219 
cond_scale: 7.0

sampling_timesteps: 500 
sample_scheduler: ddim 

use_condition_output_suffix: True
use_uid_output_suffix: False

num_samples: 8 
batch_size: 8 
length: 64

return_all_timesteps: True
