_target_: plaid.pipeline.SampleLatent

model_id: "5j007z42"
model_ckpt_dir: "/data/lux70/plaid/checkpoints/plaid-compositional"
output_root_dir: "/data/lux70/plaid/artifacts/samples/"

organism_idx: 3617
function_idx: 2219 
cond_scale: 10.0

sampling_timesteps: 500 
sample_scheduler: ddim 

num_samples: 128 
length: 256 
batch_size: -1 

beta_scheduler_name: null 
beta_scheduler_start: null
beta_scheduler_end: null
beta_scheduler_tau: null

return_all_timesteps: True
