_target_: plaid.datasets.CompressedH5DataModule
hourglass_model_id: jzlv54wl
h5_root_dir: /homefs/home/lux70/storage/data/pfam/compressed/subset_5000
max_seq_len: 512
batch_size: 128
num_workers: 8
shuffle_val_dataset: False
